version: '3.7'
services:
    selenium-hub:
        image: selenium/hub
        container_name: 'selenium-hub'
        ports:
            - 4444:4444
    chrome:
        image: selenium/node-chrome
        depends_on:
            - selenium-hub
        container_name: 'chrome'
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
    python:
        build: ./build/python3
        container_name: 'python'
        depends_on:
            - selenium-hub
        environment:
            - HUB_HOST=selenium-hub
            - HUB_PORT=4444
        command: 'tail -f /dev/null'
        working_dir: '/root/script/'
        volumes:
            - $HOME/selenium/:/root/script/
